# development:
#   adapter: postgresql
#   encoding: unicode
#   database: bookmark_manager_development
#   host: localhost
#   password:
#
# test:
#   adapter: postgresql
#   encoding: unicode
#   database: bookmark_manager_test
#   pool: 5
#   host: localhost
#   password:
